variables:
  GIT_SUBMODULE_STRATEGY: recursive

training:
  stage: build
  image: registry.gitlab.com/azae/outils/latex/gitlab
  script:
    - make all
  artifacts:
    paths:
      - crafting_unit_tests/*.pdf

#pages:
#  stage: deploy
#  image: debian:sid
#  script:
#    - apt-get update && apt-get install -y pandoc
#    - mkdir public
#    - pandoc < readme.md > public/index.html
#  artifacts:
#    paths:
#    - public
#  only:
#  - master
